[workspace]
members = [
    "nano",
    "blink_test",
    "main_test",
    "twi_test",
    "bmp_180",
    "bmp_180_test"]
default-members = ["main_test"]
resolver = "3"

[profile.dev]
overflow-checks = true # Включить проверку переполнений чисел
panic = "abort"
lto = true
opt-level = "s"

[profile.release]
panic = "abort"
lto = true
opt-level = 2

[unstable]
json-target-spec = true
