[unstable]
json-target-spec = true
build-std = ["core"]
[build]
target = ".cargo/avr-atmel-atmega328p.json"

[target.avr-atmel-atmega328p]
linker = ".cargo/avr_sh.sh"
rustflags = [
    "-C", "target-cpu=atmega328p",
    "-C", "link-arg=-mmcu=atmega328p",
    "-C", "panic=abort",
    "-C", "relocation-model=static",
    "-C", "lto=yes",
]
# runner = "avrdude -C/etc/avrdude.conf -v -patmega328p -carduino -P/dev/ttyUSB0 -b115200 -D -Uflash:w:"
runner = "./.cargo/flash.sh"
