[unstable]
# Эта магия заставит Rust собрать core и compiler_builtins под AVR
build-std = ["core"]
json-target-spec = true
[build]
target = ".cargo/avr-atmel-atmega328p.json" # Или используйте встроенный, если он есть в nightly

[target.avr-atmel-atmega328p]
#runner = ".cargo/deploy.sh" # Райвдуд сам прошьет после cargo run
linker = ".cargo/avr_sh.sh"
# Добавляем target-cpu здесь, чтобы LLVM не паниковал
rustflags = [
    "-C", "target-cpu=atmega328p",
    "-C", "link-arg=-mmcu=atmega328p",
    "-C", "panic=abort",
    "-C", "relocation-model=static",
]
#avrdude -c arduino -p m328p -P /dev/ttyUSB* -b 115200 -U flash:w:${PROJECT_NAME}.hex:i

